CREATE TABLE ENDERECO (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_PESSOA BIGINT,
ENDERECO_PRINCIPAL BOOLEAN,
LOGRADOURO VARCHAR(255),
CEP VARCHAR(8),
NUMERO VARCHAR(16),
CIDADE VARCHAR(128)
);

ALTER TABLE ENDERECO
ADD FOREIGN KEY (ID_PESSOA)
REFERENCES PESSOA(ID)